version: "3"
services:
  app:
    environment:
      DB_NAME: test-db
    command: ["/bin/sh", "-c", "chmod +x *.sh && ./wait-for-it.sh postgres-db:5432 -- npm run test"]
  db:
    environment:
      POSTGRES_DB: test-db
    volumes:
      - ./pg:/docker-entrypoint-initdb.d