# docker-compose.yml
version: "3"
services:
  app:
    build: .
    depends_on:
      - postgres
    environment:
      # DATABASE_URL: postgres://user:pass@postgres:5432/db
      DB_USERNAME: user
      DB_PASSWORD: pass
      DB_HOST: postgres
      DBM_HOST: postgres
      DB_PORT: 5432
      # NODE_ENV: development
      PORT: 3000
    ports:
      - "3000:3000"
    command: npm run dev
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  postgres:
    image: postgres:12
    restart: always
    ports:
      - "35432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db