version: "3"
services:
  app:
    build: .
    depends_on:
      - db
    environment:
      DB_USERNAME: user
      DB_PASSWORD: pass
      DB_HOST: db
      DBM_HOST: db
      DB_PORT: 5432
      # NODE_ENV: development
      PORT: 3000
    ports:
      - "3000:3000"
    command: npm run dev
    volumes:
      - .:/usr/src/app
      - app_node_modules:/usr/src/app/node_modules

  db:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db

volumes:
  app_node_modules: